### ISSUE TITLE
Support annotating k8s secrets !?

### ISSUE THREAD

**Issue by domruf** [OT-CONTAINER-KIT/k8s-vault-webhook#21]
What do you think about the idea to support annotating k8s secrets as well?

So the idea would be to create a secret like this
```
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
      annotations:
      vault.opstree.secret.manager/enabled: "true"
      vault.opstree.secret.manager/path: secret/mysql
      vault.opstree.secret.manager/role: tester
      vault.opstree.secret.manager/service: http://vault.vault:8200
data:
  MYSQL_ROOT_PASSWORD: vault:MYSQL_ROOT_PASSWORD
  MYSQL_USER1_PASSWORD: vault:MYSQL_USER1_PASSWORD
```
On creation (and updates) of this secrets, the `data.*` would automatically be/updated set.
This way the secret could be used as any other k8s secret. So if for example a third party helm chart expects a k8s secret being set it would work as well.
